<?php
namespace IwacVisualizations\Site\ResourcePageBlockLayout;

use Laminas\View\Renderer\PhpRenderer;
use Omeka\Api\Representation\AbstractResourceEntityRepresentation;
use Omeka\Site\ResourcePageBlockLayout\ResourcePageBlockLayoutInterface;

/**
 * Single resource page block that branches by item resource template.
 *
 * Each supported template renders its own partial under
 * view/common/resource-page-block-layout/visualizations/. Items whose
 * template is not in the map produce no output, so admins can wire
 * this block up once for "all items" without breaking unrelated pages.
 *
 * Add a new dashboard by appending a `template_id => 'partial-name'`
 * entry to TEMPLATE_PARTIALS and creating the matching .phtml file.
 */
class Visualizations implements ResourcePageBlockLayoutInterface
{
    /**
     * Map of resource template ids on islam.zmo.de to the partial name
     * (relative to common/resource-page-block-layout/visualizations/).
     *
     * Persons get a dedicated partial because the role facet (subject
     * vs creator) is meaningful only for them. The four non-person
     * entity types share `entity.phtml`, which renders the same panel
     * set without a facet bar and reads from the precomputed JSON
     * shape that generate_entity_dashboards.py emits.
     *
     * Audio (9), Video recording (19), YouTube video (23), Document
     * (22) and Photograph (15) dispatch to `minimal-item.phtml` — a
     * small dashboard (channel figures + sibling sparkline + a strip of
     * neighbouring items) backed by
     * `files/iwac-visualizations/template-summary.json` (generated by
     * `scripts/generate_template_summary.py`). Per-item precompute
     * would have low ROI for these; the minimal partial gives the
     * Visualizations block a meaningful presence on those pages
     * without duplicating Omeka's default metadata view.
     *
     * Templates 9, 19 and 23 all resolve to the same `audiovisual`
     * subset because the data boundary is the resource CLASS (38
     * `bibo:AudioVisualDocument`), which all three share. The template
     * only chooses the presentation. Template 23 arrived on 2026-08-12
     * with the YouTube ingest and was the case this dispatch table was
     * built to absorb: until it was listed here, every one of those
     * item pages rendered the block as nothing at all. `tests/php/run.php`
     * now asserts each mapped template resolves, so the next template
     * cannot be lost the same way.
     *
     * The eight reference templates (10 Book, 11 Book chapter, 12 Book
     * review, 13 Report, 14 Thesis, 16 Blog post, 17 Communication,
     * 18 Journal article) share `reference.phtml`. They were deliberately
     * unmapped until 2026-07: a bibliographic record carried nothing a
     * chart could add over Omeka's own item page. The pipeline's full-text
     * pass changed that — references now have embeddings, LDA topics and
     * word counts, so the partial can show the work's place in the
     * bibliography's timeline, its nearest neighbours, and the press
     * coverage it resembles. Coverage is partial (~half the bibliography
     * has extracted text), so a missing per-item JSON removes the block
     * rather than erroring.
     *
     * Photograph (15) has a history: it was mapped to the `documents`
     * HF slice until v1.3.0 — wrongly, since photographs were not
     * exported to the dataset at all, so those pages showed unrelated
     * archival documents as "siblings" — then unmapped entirely, and
     * is mapped again here because the 2026-07 pipeline added the
     * `images` subset (class 58 `bibo:Image`). Photographs are in fact
     * the *best*-served template of the four: `embedding_image` is a
     * multimodal vector of the picture itself, so their neighbour
     * strip is real similarity rather than a recency list.
     */
    const TEMPLATE_PARTIALS = [
        5 => 'person',         // Personnes
        6 => 'entity',         // Lieux
        7 => 'entity',         // Organisations
        3 => 'entity',         // Sujets
        2 => 'entity',         // Événements
        8 => 'article',        // bibo:Article (Article de presse)
        21 => 'publication',   // bibo:Issue (Publication islamique)
        9 => 'minimal-item',   // Audio
        19 => 'minimal-item',  // Video recording
        23 => 'minimal-item',  // YouTube video
        22 => 'minimal-item',  // Document
        15 => 'minimal-item',  // Photograph
        10 => 'reference',     // Book
        11 => 'reference',     // Book chapter
        12 => 'reference',     // Book review
        13 => 'reference',     // Report
        14 => 'reference',     // Thesis / dissertation
        16 => 'reference',     // Blog post
        17 => 'reference',     // Communication
        18 => 'reference',     // Journal article
    ];

    public function getLabel(): string
    {
        return 'Visualisations'; // @translate
    }

    public function getCompatibleResourceNames(): array
    {
        return ['items'];
    }

    public function render(PhpRenderer $view, AbstractResourceEntityRepresentation $resource): string
    {
        $template = $resource->resourceTemplate();
        if (!$template) {
            return '';
        }

        $partial = self::TEMPLATE_PARTIALS[(int) $template->id()] ?? null;
        if ($partial === null) {
            return '';
        }

        return $view->partial(
            'common/resource-page-block-layout/visualizations/' . $partial,
            ['resource' => $resource]
        );
    }
}
