<?php
// GENERATED by scripts/build-embed-tokens.js from tokens.json (IWAC-theme 2.23.0).
// Do not edit: run `npm run build:embed-tokens` after `npm run sync:tokens` in IWAC-theme.
//
// The theme's brand seeds. layout/embed.phtml skips its brand-accent
// override when a setting equals its seed: the embed token sheet already
// carries the theme's derivation of that seed.
return [
    'primary'   => '#e64a19',
    'secondary' => '#394f68',
    'fontsUrl'  => 'https://fonts.bunny.net/css?family=besley:500,600,800|public-sans:ital,wght@0,400..700;1,400|source-serif-4:ital,opsz,wght@0,8..60,400..600;1,8..60,400&display=swap',
];
