<?php
// GENERATED by scripts/build-embed-tokens.js from tokens.json (IWAC-theme 2.23.0).
// Do not edit: run `npm run build:embed-tokens` after `npm run sync:tokens` in IWAC-theme.
//
// The theme's brand seeds. layout/embed.phtml skips its brand-accent
// override when a setting equals its seed: the embed token sheet already
// carries the theme's derivation of that seed.
return [
    'primary'   => '#e64a19',
    'secondary' => '#394f68',
];
