<?php
declare(strict_types=1);
namespace IwacVisualizations\Sentiment;

// Generated by scripts/build-model-registry.js from config/sentiment-models.json.
final class ModelRegistry
{
    public const STEMS = ['gemini', 'chatgpt', 'mistral', 'gpt56Luna', 'mistralSmall2603', 'deepseekV4Flash0731', 'gemma431bIt', 'qwen3827b', 'deepseekV4Flash', 'gemini35FlashLite', 'gemini36Flash', 'qwen35A3b', 'qwen35A10b'];
    public const MODELS = ['gpt56Luna', 'mistralSmall2603', 'deepseekV4Flash0731', 'gemma431bIt', 'qwen3827b'];
    public const INFO = ['gpt56Luna' => ['name' => 'GPT-5.6 Luna', 'org' => 'OpenAI', 'short' => 'GPT-5.6 Luna', 'logo' => 'ChatGPT_logo.svg'], 'mistralSmall2603' => ['name' => 'Mistral Small 4', 'org' => 'Mistral AI', 'short' => 'Mistral Small 4', 'logo' => 'Mistral_AI_logo.svg'], 'deepseekV4Flash0731' => ['name' => 'DeepSeek V4 Flash', 'org' => 'DeepSeek', 'short' => 'DeepSeek V4 Flash', 'logo' => 'DeepSeek_logo.svg'], 'gemma431bIt' => ['name' => 'Gemma 4 31B', 'org' => 'Google DeepMind', 'short' => 'Gemma 4 31B', 'logo' => 'Gemma_logo.png'], 'qwen3827b' => ['name' => 'Qwen3.8 27B', 'org' => 'Alibaba Cloud', 'short' => 'Qwen3.8 27B', 'logo' => 'Qwen_logo.png']];
}
