#!/usr/bin/env node
/**
 * Extract the PHP-side translatable strings into language/template.pot, and
 * (with --check) prove the committed catalogues still cover the sources.
 *
 * Why this exists: there is no `xgettext` on the machines this module is
 * built on (language/README.md carries the recipe for machines that have
 * it), so the template was regenerated by hand — and drifted. At v1.58.0 the
 * six `// @translate` strings of the On This Day block form were in neither
 * template.pot nor fr.po, so French admins read them in English, and four
 * entries in the pot named strings the sources no longer contained. Nothing
 * could see either: `lint:i18n-mo` proves fr.mo matches fr.po, but nothing
 * proved fr.po matched the code.
 *
 * What is extracted — the same two things the documented xgettext recipe
 * finds:
 *
 *   1. `translate('…')` / `->translate("…")` calls whose FIRST argument is a
 *      string literal, single- or double-quoted, including literals joined
 *      with `.` across lines (`'Which layout ' . 'the block opens on.'`).
 *      A call whose first argument is not a literal (`translate($label)`,
 *      `translate($this->row()['description'])`) is a runtime lookup of a
 *      string extracted elsewhere, and is skipped.
 *   2. Any string literal on a line that ends in the `// @translate` marker —
 *      the Omeka convention for strings that reach `translate()` indirectly
 *      (form labels, option values, block-layout metadata).
 *
 * Sources: Module.php, config/, src/, view/ — every .php and .phtml.
 *
 * Modes:
 *   node scripts/extract-pot.js           rewrite language/template.pot
 *   node scripts/extract-pot.js --check   exit 1 if any source string is
 *                                         missing from template.pot or from
 *                                         fr.po, or if the pot carries a
 *                                         string the sources no longer do
 *
 * The pot is written in source order, one entry per distinct msgid, with
 * the header carried over from the existing file so the metadata is not
 * reset on every run. Dynamic lookups such as the sentiment vocabulary
 * (`Central`, `Marginal`, …) are declared once in Module.php with
 * `@translate` markers, so they are extracted like any other literal.
 */
'use strict';

const { readFileSync, readdirSync, statSync, writeFileSync } = require('fs');
const { join, relative } = require('path');

const { catalogueFromPo, parsePo } = require('./gettext');

const ROOT = join(__dirname, '..');
const LANGUAGE = join(ROOT, 'language');
const POT = join(LANGUAGE, 'template.pot');
const PO = join(LANGUAGE, 'fr.po');
const SOURCE_ROOTS = ['Module.php', 'config', 'src', 'view'];

const check = process.argv.includes('--check');

/* ------------------------------------------------------------------------ */
/*  Source walk                                                              */
/* ------------------------------------------------------------------------ */

function walk(entry, out) {
    const abs = join(ROOT, entry);
    const stat = statSync(abs);
    if (stat.isFile()) {
        if (/\.(php|phtml)$/.test(entry)) out.push(entry);
        return;
    }
    for (const name of readdirSync(abs).sort()) {
        walk(join(entry, name), out);
    }
}

function sourceFiles() {
    const files = [];
    for (const root of SOURCE_ROOTS) walk(root, files);
    return files.map((f) => relative(ROOT, join(ROOT, f)).split('\\').join('/'));
}

/* ------------------------------------------------------------------------ */
/*  PHP string literals                                                      */
/* ------------------------------------------------------------------------ */

/**
 * Decode one PHP string literal. Single-quoted strings know only `\'` and
 * `\\`; double-quoted ones take the C-style escapes gettext also uses. No
 * interpolation is attempted — a `$` inside a double-quoted translatable
 * string would be a bug in the source, and none exists.
 */
function decodeLiteral(literal) {
    const quote = literal[0];
    const body = literal.slice(1, -1);
    if (quote === "'") {
        return body.replace(/\\(['\\])/g, '$1');
    }
    return body.replace(/\\([nrtv"\\$])/g, (match, escape) => ({
        n: '\n', r: '\r', t: '\t', v: '\v', '"': '"', '\\': '\\', $: '$',
    })[escape]);
}

// One PHP string literal, either quoting.
const LITERAL = /'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"/;
// A run of literals joined with `.` and any whitespace (newlines included).
// Both occurrences of LITERAL are grouped: its two quoting branches are an
// alternation, and an ungrouped first occurrence binds the `(…)*` tail to the
// double-quoted branch alone — which is how a four-line single-quoted
// concatenation was once read as its first line only.
const CONCAT = new RegExp(`(?:${LITERAL.source})(?:\\s*\\.\\s*(?:${LITERAL.source}))*`);

function joinConcat(text) {
    const parts = [];
    const one = new RegExp(LITERAL.source, 'g');
    let m;
    while ((m = one.exec(text)) !== null) parts.push(decodeLiteral(m[0]));
    return parts.join('');
}

/**
 * Blank out comments so a `translate('…')` inside a docblock example (the
 * usage block at the top of iwac-block-shell.phtml has three) is not read as
 * a call. Block comments go entirely; a `//` comment goes when it is the
 * whole line. The `// @translate` markers are found on the ORIGINAL source
 * below, so a trailing marker after code is unaffected. Newlines are kept so
 * line numbers stay right.
 */
function stripComments(source) {
    return source
        .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
        .replace(/^[ \t]*(?:\/\/|\*)[^\n]*/gm, (m) => m.replace(/[^\n]/g, ' '));
}

/** Every translatable string in one PHP source, in order, with its line. */
function extractFromSource(source) {
    const found = [];
    const code = stripComments(source);

    // 1. translate('…' [. '…']…) — first argument a literal chain.
    const call = new RegExp(`\\btranslate\\s*\\(\\s*(${CONCAT.source})`, 'g');
    let m;
    while ((m = call.exec(code)) !== null) {
        found.push({ id: joinConcat(m[1]), offset: m.index });
    }

    // 2. `// @translate` markers: the LAST literal chain of the statement
    //    the marker ends — which is the value in `'label' => 'Text', //
    //    @translate`, not the key, and the whole joined string when the
    //    statement's earlier lines are continuations of one concatenation
    //    (`'Which layout ' \n . 'the block opens on.'); // @translate`).
    //    A continuation line is one that starts with `.`; the look-back
    //    stops at the first line that does not.
    const marker = /\/\/\s*@translate\b/g;
    while ((m = marker.exec(source)) !== null) {
        let start = source.lastIndexOf('\n', m.index) + 1;
        let region = source.slice(start, m.index);
        while (/^\s*\./.test(region) && start > 0) {
            const prevStart = source.lastIndexOf('\n', start - 2) + 1;
            region = source.slice(prevStart, start - 1) + '\n' + region;
            start = prevStart;
        }
        const chain = new RegExp(CONCAT.source, 'g');
        let last = null;
        let c;
        while ((c = chain.exec(region)) !== null) last = c[0];
        if (last !== null) {
            const id = joinConcat(last);
            if (id !== '') found.push({ id, offset: m.index });
        }
    }

    found.sort((a, b) => a.offset - b.offset);
    return found.map((f) => ({
        id: f.id,
        line: source.slice(0, f.offset).split('\n').length,
    }));
}

/* ------------------------------------------------------------------------ */
/*  Collect                                                                  */
/* ------------------------------------------------------------------------ */

const strings = new Map(); // msgid → [{ file, line }]
for (const file of sourceFiles()) {
    const source = readFileSync(join(ROOT, file), 'utf8');
    for (const { id, line } of extractFromSource(source)) {
        if (!strings.has(id)) strings.set(id, []);
        strings.get(id).push({ file, line });
    }
}

/* ------------------------------------------------------------------------ */
/*  Write or check                                                           */
/* ------------------------------------------------------------------------ */

function quote(text) {
    return '"' + text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}

function existingHeader() {
    let raw = '';
    try { raw = readFileSync(POT, 'utf8'); } catch (e) { raw = ''; }
    const m = /^msgid ""\nmsgstr ""\n((?:"[^\n]*"\n)+)/m.exec(raw);
    if (m) return m[1];
    return [
        'Project-Id-Version: IwacVisualizations\\n',
        'Report-Msgid-Bugs-To: \\n',
        'POT-Creation-Date: YEAR-MO-DA HO:MI+ZONE\\n',
        'PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n',
        'Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n',
        'Language-Team: LANGUAGE <LL@li.org>\\n',
        'MIME-Version: 1.0\\n',
        'Content-Type: text/plain; charset=UTF-8\\n',
        'Content-Transfer-Encoding: 8bit\\n',
    ].map((l) => `"${l}"\n`).join('');
}

function render() {
    let out = '#\nmsgid ""\nmsgstr ""\n' + existingHeader() + '\n';
    for (const [id, sites] of strings) {
        out += `#: ${sites.map((s) => `${s.file}:${s.line}`).join(' ')}\n`;
        out += `msgid ${quote(id)}\nmsgstr ""\n\n`;
    }
    return out;
}

function loadIds(path, label) {
    const entries = parsePo(readFileSync(path, 'utf8'), label);
    return new Set(entries.map((e) => e.id).filter((id) => id !== ''));
}

if (!check) {
    writeFileSync(POT, render(), 'utf8');
    console.log(`✓ pot: ${strings.size} strings from ${sourceFiles().length} PHP sources → language/template.pot`);
    process.exit(0);
}

const potIds = loadIds(POT, 'language/template.pot');
const poEntries = parsePo(readFileSync(PO, 'utf8'), 'language/fr.po');
const poIds = new Set(poEntries.map((e) => e.id).filter((id) => id !== ''));
const poTranslated = catalogueFromPo(poEntries, 'language/fr.po');

const notInPot = [...strings.keys()].filter((id) => !potIds.has(id));
const notInPo = [...strings.keys()].filter((id) => !poIds.has(id));
const untranslated = [...strings.keys()].filter((id) => poIds.has(id) && !poTranslated.has(id));
const stalePot = [...potIds].filter((id) => !strings.has(id));

const clip = (s) => JSON.stringify(s.length > 90 ? `${s.slice(0, 90)}…` : s);
const where = (id) => strings.get(id).map((s) => `${s.file}:${s.line}`).join(', ');

if (notInPot.length || notInPo.length || untranslated.length || stalePot.length) {
    console.error('\n✗ pot guard: the PHP sources and the catalogues disagree\n');
    const report = (heading, ids, detail) => {
        if (!ids.length) return;
        console.error(`  ${heading} (${ids.length}):`);
        for (const id of ids.slice(0, 20)) console.error(`    ${clip(id)}${detail ? `  — ${detail(id)}` : ''}`);
        if (ids.length > 20) console.error(`    … and ${ids.length - 20} more`);
        console.error('');
    };
    report('in the sources but not in language/template.pot', notInPot, where);
    report('in the sources but not in language/fr.po — French readers get English', notInPo, where);
    report('in fr.po but without a French translation', untranslated, where);
    report('in template.pot but no longer in any source', stalePot);
    console.error('  Regenerate the template with: node scripts/extract-pot.js');
    console.error('  then add the French for the new msgids to fr.po and run: npm run build:mo\n');
    process.exit(1);
}

console.log(`✓ pot guard: ${strings.size} source strings, all in template.pot and translated in fr.po`);
